# Name of your application. Used to uniquely configure containers.
service: attendance-hub

# Name of the container image.
image: alricthe/attendance-hub

# Deploy to these servers.
servers:
  web:
    - 66.181.46.14

# We are disabling the proxy host and SSL for the demo
# so you can access the app directly via your IP address.
# proxy:
#   ssl: true
#   host: app.example.com

# Credentials for your image host.
registry:
  username: alricthe
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Persistent storage volume for SQLite.
volumes:
  - "attendance_hub_storage:/rails/storage"

# asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
  driver: docker